# LISTS

with Hetrogenious data types

In [2]:
# Creating a list with mixed data types
my_list = [1, 'hello', 3.14, True]

# Accessing elements
print("List:", my_list)
print("First element:", my_list[0])
print("First element:", my_list[1])
print("First element:", my_list[2])
print("First element:", my_list[3])

# Adding elements
my_list.append(42)
print("After adding 42:", my_list)
my_list.append('we')
print(my_list)



List: [1, 'hello', 3.14, True]
First element: 1
First element: hello
First element: 3.14
First element: True
After adding 42: [1, 'hello', 3.14, True, 42]
[1, 'hello', 3.14, True, 42, 'we']


# `Numpy`

NumPy arrays are homogeneous, meaning all elements must be of the same data type.
This allows for more efficient and faster operations
NumPy arrays are more memory-efficient and provide faster numerical operations compared to lists, especially for large datasets.

Lists are more flexible but can be slower for numerical computations.

In [2]:
import numpy as np

# Creating a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Accessing elements
print("NumPy Array:", my_array)
print("First element:", my_array[0])

# Adding elements
# Note: NumPy arrays are fixed-size, so you can't directly append, but you can create a new array
new_array = np.append(my_array, 6)
print("After adding 6:", new_array)


NumPy Array: [1 2 3 4 5]
First element: 1
After adding 6: [1 2 3 4 5 6]


a. Creating an Empty NumPy Array


In [3]:
import numpy as np
arr = np.array([])
print(arr)
print(type(arr))

[]
<class 'numpy.ndarray'>


In [4]:
print("array: ", arr)
print("arr.ndim: ", arr.ndim)   # get number of dimensions (an empty array has number of dimensions equals to 1)
print("arr.shape: ", arr.shape) # This is an empty array, so have a shape of (0, )
print("arr.size: ", arr.size)   # get total number of elements
print("arr.dtype: ", arr.dtype) # get data type, default for empty array is float64
print("arr.itemsize: ", arr.itemsize)  # get size in bytes of each element of the array default is 8 for float64
print("arr.nbytes: ", arr.nbytes)  # get number of bytes occupied by entire array object in memory
print("arr.data: ", arr.data)
print("arr.strides: ", arr.strides)
print("arr.flags: \n", arr.flags)

array:  []
arr.ndim:  1
arr.shape:  (0,)
arr.size:  0
arr.dtype:  float64
arr.itemsize:  8
arr.nbytes:  0
arr.data:  <memory at 0x78fac41c04c0>
arr.strides:  (0,)
arr.flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [5]:
import numpy as np
arr = np.array([10])

# Retrieve the element using indexing
value = arr[0]

print("Retrieved value:", value)


Retrieved value: 10


b. 0-Dimensional Array

In [6]:
# Create a 0-D numpy array using array() constructor
import numpy as np
arr = np.array(10)
print("array: ", arr)

array:  10


Arithmetic Operations
a. Arithmetic Operations on 1-D Arrays

In [7]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)

# After the operation a new `ndarray` is returned
print("np.add(arr1, arr2) = ",      arr1 + arr2)     # np.add(arr1, arr2)
print("np.subtract(arr1, arr2) = ", arr1 - arr2)     # np.subtract(arr1, arr2)
print("np.multiply(arr1, arr2) = ", arr1 * arr2)     # np.multiply(arr1, arr2)
print("np.divide(arr1, arr2) = ",   arr1  / arr2)    # np.divide(arr1, arr2)
print("np.mod(arr1, arr2) = ",      arr1  % arr2)    # np.mod(arr1, arr2) # np.remainder(arr1, arr2)

arr1:  [5 6 8 2]
arr2:  [5 4 7 4]
np.add(arr1, arr2) =  [10 10 15  6]
np.subtract(arr1, arr2) =  [ 0  2  1 -2]
np.multiply(arr1, arr2) =  [25 24 56  8]
np.divide(arr1, arr2) =  [1.         1.5        1.14285714 0.5       ]
np.mod(arr1, arr2) =  [0 2 1 2]


b. Arithmetic Operations on 2-D Arrays

In [8]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)

# After the operation a new `ndarray` is returned
print("np.add(matrix1 , matrix2) = \n",      matrix1 + matrix2) # np.add(matrix1 , matrix2)
print("np.subtract(matrix1 , matrix2) = \n", matrix1 - matrix2) # np.subtract(matrix1 , matrix2)
print("np.multiply(matrix1 , matrix2) = \n", matrix1 * matrix2) # np.multiply(matrix1 , matrix2)
print("np.divide(matrix1 , matrix2) = \n",   matrix1 / matrix2) # np.divide(matrix1 , matrix2)
print("np.mod(matrix1 , matrix2) = \n",      matrix1 % matrix2) # np.remainder(matrix1 , matrix2)

matrix1: 
 [[5 9]
 [3 6]]
matrix2: 
 [[3 8]
 [2 1]]
np.add(matrix1 , matrix2) = 
 [[ 8 17]
 [ 5  7]]
np.subtract(matrix1 , matrix2) = 
 [[2 1]
 [1 5]]
np.multiply(matrix1 , matrix2) = 
 [[15 72]
 [ 6  6]]
np.divide(matrix1 , matrix2) = 
 [[1.66666667 1.125     ]
 [1.5        6.        ]]
np.mod(matrix1 , matrix2) = 
 [[2 1]
 [1 0]]


3. More Mathematical Operations
a. Mathematical Operations on 1-D Array

In [9]:
# Creating 1-D array of 5 elements of random floats between 1 and 10
arr = np.random.rand(5)*10
print("Original ndarray: ", arr)


# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.abs(arr) = ", np.abs(arr))
print("np.square(arr) = ", np.square(arr))
print("np.sqrt(arr) = ", np.sqrt(arr))
print("np.cbrt(arr) = ", np.cbrt(arr))
print("np.log(arr) = ", np.log(arr))
print("np.log2(arr) = ", np.log2(arr))
print("np.log10(arr) = ", np.log10(arr))
print("np.isnan(arr) = ", np.isnan(arr))
print("np.ceil(arr) = ", np.ceil(arr))
print("np.floor(arr) = ", np.floor(arr))
print("np.cumsum(arr) = ", np.cumsum(arr))

Original ndarray:  [8.4405064  6.20803964 6.20314483 6.2794219  8.14589268]
np.abs(arr) =  [8.4405064  6.20803964 6.20314483 6.2794219  8.14589268]
np.square(arr) =  [71.24214821 38.53975619 38.47900581 39.43113942 66.3555676 ]
np.sqrt(arr) =  [2.90525496 2.4915938  2.49061134 2.50587747 2.85410103]
np.cbrt(arr) =  [2.03605498 1.83788427 1.83740111 1.84490166 2.01208456]
np.log(arr) =  [2.13304231 1.82584517 1.82505639 1.83727792 2.09751383]
np.log2(arr) =  [3.07732956 2.63413777 2.63299981 2.65063175 3.02607281]
np.log10(arr) =  [0.9263685  0.79295448 0.79261192 0.79791966 0.91093868]
np.isnan(arr) =  [False False False False False]
np.ceil(arr) =  [9. 7. 7. 7. 9.]
np.floor(arr) =  [8. 6. 6. 6. 8.]
np.cumsum(arr) =  [ 8.4405064  14.64854604 20.85169087 27.13111277 35.27700545]


b. Mathematical Operations on 2-D Array

In [ ]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix = np.random.randint(1,10, size=(2, 2))
print("matrix: \n", matrix)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.square(matrix) = \n", np.square(matrix))
print("np.sqrt(matrix) = \n", np.sqrt(matrix))
print("np.log2(matrix) = \n", np.log2(matrix))
print("np.isnan(matrix) = \n", np.isnan(matrix))
print("np.ceil(matrix) = \n", np.ceil(matrix))
print("np.floor(matrix) = \n", np.floor(matrix))
print("np.cumsum(matrix) = \n", np.cumsum(matrix))

4. Aggregate Functions
a. Aggregate Functions on 1-D Arrays

In [10]:
# Create a 1-D array having 5 random integers from 1 to 9
arr = np.random.randint(1, 10, size=5)
print("arr: ", arr)

# After the operation a new `ndarray` is returned, which is a copy of the original array with the operation performed
print("np.min(arr) = ",     np.min(arr))
print("np.max(arr) = ",     np.max(arr))
print("np.sum(arr) = ",     np.sum(arr))
print("np.prod(arr) = ", np.prod(arr))

arr:  [3 5 4 1 7]
np.min(arr) =  1
np.max(arr) =  7
np.sum(arr) =  20
np.prod(arr) =  420


5. Comparing NumPy Arrays
a. Comparing NumPy 1-D Arrays
Returns a Boolean numpy array containing True/False after doing element wise comparison

In [ ]:
import numpy as np
# Create two 1-D arrays each having 4 random integers from 1 to 9
arr1 = np.random.randint(1,10, size=4)
arr2 = np.random.randint(1,10, size=4)
print("arr1: ", arr1)
print("arr2: ", arr2)
print("np.equal(arr1, arr2) = ",      arr1 == arr2)      # np.equal(arr1, arr2)
print("np.not_equal(arr1, arr2) = ",  arr1 != arr2)      # np.not_equal(arr1, arr2)

print("np.greater(arr1, arr2) = ",      arr1 > arr2)     # np.greater(arr1, arr2)
print("np.greater_equal(arr1, arr2) = ",  arr1 >= arr2)  # np.greater_equal(arr1, arr2)

print("np.less(arr1, arr2) = ",      arr1 < arr2)        # np.less(arr1, arr2)
print("np.less_equal(arr1, arr2) = ",  arr1 <= arr2)     # np.less_equal(arr1, arr2)

b. Comparing NumPy 2-D Arrays

In [ ]:
import numpy as np
# Create a 2x2 matrix with random integers  between 1 to 9
matrix1 = np.random.randint(1,10, size=(2, 2))
matrix2 = np.random.randint(1, 10, size=(2, 2))
print("matrix1: \n", matrix1)
print("matrix2: \n", matrix2)



print("np.equal(matrix1, matrix2) = \n",        matrix1 == matrix2)
print("np.not_equal(matrix1, matrix2) = \n",    matrix1 != matrix2)

print("np.greater(matrix1, matrix2) = \n",      matrix1 > matrix2)
print("np.greater_equal(matrix1, matrix2) = \n",matrix1 >= matrix2)

print("np.less(matrix1, matrix2) = \n",         matrix1 < matrix2)
print("np.less_equal(matrix1, matrix2) = \n",   matrix1 <= matrix2)

matrix1: 
 [[2 7]
 [4 9]]
matrix2: 
 [[2 3]
 [5 1]]
np.equal(matrix1, matrix2) = 
 [[ True False]
 [False False]]
np.not_equal(matrix1, matrix2) = 
 [[False  True]
 [ True  True]]
np.greater(matrix1, matrix2) = 
 [[False  True]
 [False  True]]
np.greater_equal(matrix1, matrix2) = 
 [[ True  True]
 [False  True]]
np.less(matrix1, matrix2) = 
 [[False False]
 [ True False]]
np.less_equal(matrix1, matrix2) = 
 [[ True False]
 [ True False]]
